### ISSUE TITLE
List of Files

### ISSUE THREAD

**Issue by riyuk** [alessandrobelli/NotionHook#1]
Hey.

I've seen this on another action - maybe you can adopt things of it to create a list of files which changed and add it to the Notion Body/Description?

-> https://github.com/jitterbit/get-changed-files/blob/master/src/main.ts

Basicly he uses the github api (https://developer.github.com/v3/repos/commits/#compare-two-commits). Maybe it makes sense to omit the filelist if the API is throwing a error or something unexpected happens?

**Comment by alessandrobelli** [comment]
Thanks a lot for the tip! I'll try to develop this right now. Do you think I should mention them or something similar?
