### ISSUE TITLE
Example database is incorrect

### ISSUE THREAD

**Issue by WardToulet** [alessandrobelli/NotionHook#2]
Two collumns are not named as expected.

- `Description` should be spelled `description`
- `id` should be spelled `Id`

It would be more logical for them to be all capitalized as that is the pattern used. 

After changing this everything works great. 

I haven't had the time to dive into the code and fix it myself but this should be a minor fix.

**Comment by alessandrobelli** [comment]
Hi!
Sorry, I don't understand, why
> `Description` should be spelled `description`

but then 

> It would be more logical for them to be all capitalized as that is the pattern used.

I agree with the last statement, and I'll capitalize `id` to `Id` in the template :)
