### ISSUE TITLE
Could not find database with ID

### ISSUE THREAD

**Issue by marlisumarli** [alessandrobelli/NotionHook#3]
`@notionhq/client warn: request fail {
  code: 'object_not_found',
  message: 'Could not find database with ID: bdc6e606-7314-4e6a-90ff-e8906c219bc4. Make sure the relevant pages and databases are shared with your integration.'
}`

Unable to connect to Notion with the above code. 
Even though I have followed the steps correctly.

**Comment by alexisRippstein** [comment]
@marlisumarli, i had the same problem. 
After sharing the relevant page with my integration, everything works fine.

Here you can find the steps on how to do that:
https://developers.notion.com/docs/create-a-notion-integration#step-2-share-a-database-with-your-integration

**Comment by marlisumarli** [comment]
Many thanks you sir. 🙏🏻
